effortlessfolder/effortless/urls.py
from django.contrib import admin
from django.urls import path, include

# 각 앱마다 url 연결
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('ott.urls')),
    path('', include('review.urls')),
]

effortlessfolder/ott/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# ott 관련 url
app_name = 'ott'
urlpatterns = [
    path('', views.main, name ='main'),
    path('amazon/', views.amazon, name='amazon'),
    path('hulu/', views.hulu, name='hulu'),
    path('disney/', views.disney, name='disney'),
    path('netflix/', views.netflix, name='netflix'),
    
    

    


]

effortlessfolder/review/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# 리뷰 관련 url 
app_name = 'review'
urlpatterns = [
    
    path('posts/', views.post_list, name='post-list'),
    path('posts/new', views.post_create, name='post-create'),
    path('posts/<int:post_id>/', views.post_detail, name='post-detail'),
    path('posts/<int:post_id>/edit', views.post_update, name='post-update'),
    path('posts/<int:post_id>/delete', views.post_delete, name='post-delete'),
    # path('posts/search', views.search, name='search'),

    
    

    


]

effortlessfolder/review/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

#글의 제목, 내용, 작성일, 마지막 수정일 
#balnk = False > 기본 옵션 인자- 폼에 빈칸 허용할지 설정
class Post(models.Model):
    title = models.CharField(max_length=50, unique =True, error_messages={'unique':'이미 있는 제목입니다.'})
    content = models.TextField(null=True)
    dt_created = models.DateTimeField(verbose_name="Date Created", auto_now_add=True)
    dt_modified = models.DateTimeField(verbose_name="Date Modified", auto_now = True)
    writer = models.ForeignKey(User, verbose_name = "작성자", on_delete = models.CASCADE)
    

    def __str__(self):
        return self.title

effortlessfolder/review/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content']
        

    

effortlessfolder/review/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from django.db.models import Q


# Create your views here.
#리뷰 조회 목록 구현
def post_list(request):
    posts = Post.objects.all()
    context = {"posts":posts}
    

    return render(request, 'review/post_list.html', context)
# 리뷰 세부 페이지 구현
def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {"post" : post}
    return render(request, 'review/post_detail.html', context)

# 리뷰 생성
def post_create(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        # 유효성 검사를 통과하면 데이터베이스에 저장
        if post_form.is_valid():
            new_post = post_form.save()
            return redirect('review:post-detail', post_id = new_post.id )
        
        

    else:
        post_form = PostForm()
    return render(request, 'review/post_form.html', {'form' : post_form})

# 리뷰 수정
def post_update(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method =='POST':
        post_form = PostForm(request.POST, instance=post)
        if post_form.is_valid():
            post_form.save()
            return redirect('review:post-detail', post_id=post.id)
    else:
        post_form = PostForm(instance=post)
    return render(request, 'review/post_form.html', {'form' : post_form})
# 리뷰 삭제 
def post_delete(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method =='POST':
        post.delete()
        return redirect('review:post-list')
    else:
        return render(request, 'review/post_confirm_delete.html', {'post': post})

effortlessfolder/review/templates/review/base.html
<!--
	review 템플릿의 base.html입니다.
	모든 페이지에 동일하게 적용되는 속성들을 base.html에 작성하여 템플릿 확장에 사용합니다.
    review 템플릿에서는 리뷰 작성 기능 구현을 중점으로 페이지를 제작합니다.
-->

{% load static %}<!--static 폴더(css,img파일)를 로드-->
<!DOCTYPE HTML>

<!--
	Landed by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

<html>
	<head>
        <title>effortless</title>
        <meta charset='UTF-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href='../../static/review/css/main.css' %/>
		<noscript><link rel="stylesheet" href='../../static/review/css/noscript.css' /></noscript>
    </head>

    <body class="is-preload">
        <div id="page-wrapper">
            <!-- Header -->
                <header id="header"><!--상단의 네비게이션바-->
                    <h1 id="logo"><a href="{% url 'ott:main' %}">Effortless</a></h1><!--네비게이션 바 좌측의 Effortless 클릭 시 메인페이지로 이동-->
                    <nav id="nav">
						<ul>
							<li><!--메인 페이지로 이동하는 링크-->
                                <a style=" font-size:15px;" href="{% url 'ott:main' %}">Home</a>
                            </li>
						</ul>
					</nav>
                    {% block header %}<!--템플릿 확장 시 header block 내용 추가를 위한 블럭-->

                    {% endblock %}
                </header>

            <!-- Main -->
                {% block main1 %}<!--템플릿 확장 시 main1 block 내용 추가를 위한 블럭-->

                {% endblock %}

            <!-- Footer -->
                <footer id="footer"><!--모든 페이지의 하단에 위치할 footer 작성-->
                    <ul class="copyright">
                        <li>최대효율의 법칙. All rights reserved.</li>
                    </ul>
                </footer>
        </div>
        {% block style %}<!--각 페이지의 stylesheet 내용 추가를 위한 블럭-->
        {% endblock %}
    </body>
</html>

effortlessfolder/review/templates/review/post_confirm_delete.html
<!--
	review 템플릿의 post_confirm_delete.html입니다.
	작성한 리뷰를 삭제하기 전에 확인을 거치는 용도의 페이지 입니다.
-->

{% extends './base.html' %}<!--review템플릿의 base.html 템플릿 확장-->

{% block main1 %}<!--메인에 들어갈 내용 작성 시작-->
<div id="main" class="wrapper style1">
	<div align = "center" class="container">
		<p style=" font-size:23px; font-weight: 500;">{{post.title}}</p>
		<p style=" font-size:18px;">삭제하시겠습니까?</p>
		<section id="content">
			<form method="POST">
			{% csrf_token %}<!--사용자의 의도와 관계 없이 행해지는 공격 방어-->
			<input id="button" type = "submit" value="삭제하기">
			</form>
		</section>
	</div>
</div>
{% endblock %}

{% block style %}<!--각 페이지별 스타일시트 적용 부분 시작-->
    <style>
	/*버튼*/
	#button{
        border:none;
        border-radius: 7px;
        background-color:#e44c65;
        color:white;
        width:150px;
        height:40px;
		line-height: 40px;
        display: inline-block;
        vertical-align: top;
        font-size: 15px;
        cursor: pointer;
        margin-top: 20px;
		margin-bottom: 0;
		box-shadow: none;
    }
	/*기타*/
	form{
		margin:0;
	}
	#main{
		padding-top:200px;
		padding-bottom: 200px;
	}
	input{
		border:none;
		margin-bottom: 0;
	}

    </style>
{% endblock %}

effortlessfolder/review/templates/review/post_detail.html
<!--
	review 템플릿의 postdetail.html입니다.
	리뷰 목록에서 작성된 리뷰를 선택 시 리뷰 수정 삭제 및 열람이 가능하도록 하는 페이지입니다.
-->

{% extends './base.html' %}<!--review템플릿의 base.html 템플릿 확장-->

{% block main1 %}<!--메인에 들어갈 내용 작성 시작-->
<div id="main">
	<div class="container">
		<header class="major">
			<h2 style=" font-size:25px; font-weight: 500;">{{post.title}}</h2><!--선택한 리뷰의 제목-->
		</header>
		<section id="content">
			<div style=" font-size:18px;"> 작성일 </div>
            <div style=" font-size:15px;">{{post.dt_created}}</div><!--선택한 리뷰의 작성일-->
            <br>
			<hr>
			<div class="my-box" style=" font-size:15px;">{{post.content|linebreaksbr}}</div><!--선택한 리뷰의 내용-->
			<hr>

            <div id="buts"><!--돌아가기, 수정하기, 삭제하기 버튼-->
                <a href= {% url 'review:post-list' %} > <button id="button" style = "  font-size : 15px; font-weight:500; color : white;"> 돌아가기 </button> </a>
                &nbsp;
                <a href= {% url 'review:post-update' post.id %}  > <button id="button" style = " font-size : 15px; font-weight:500; color : white;"> 수정하기 </button> </a>
                &nbsp;
                <a href= {% url 'review:post-delete' post.id %} > <button id="button" style = " font-size : 15px; font-weight:500; color : white;"> 삭제하기 </button> </a>
            </div>
            
        </section>
    </div>
</div>
{% endblock main1 %}

{% block style %}<!--각 페이지별 스타일시트 적용 부분 시작-->
<style>
    /*버튼*/
    #buts{
        padding-top: 20px;
        text-align: center;
    }
    #button{
        border:none;
        border-radius: 7px;
        background-color:#e44c65;
        color:white;
        width:130px;
        height:40px;
        display: inline-block;
        vertical-align: top;
        font-size: 13px;
        cursor: pointer;
        margin-right: 10px;
    }	
    /*리뷰*/
    h2{
        margin:0px;
    }
    .container{
        margin:auto;
        width:800px;
        padding-top:100px;
        padding-bottom: 100px;
    }
    .my-box {
        border:1px solid #e44c65; padding:15px;
        border-radius: 10px;
    }
    /*기타*/
    header{
        margin-bottom: 15px;
    }
    hr{
        margin:10px;
    }

</style>
{% endblock %}

effortlessfolder/review/templates/review/post_form.html
<!--
	review 템플릿의 post_form.html입니다.
	리뷰 작성을 위한 폼을 구현한 페이지입니다.
-->

{% extends './base.html' %}<!--review템플릿의 base.html 템플릿 확장-->

{% block main1 %}<!--메인에 들어갈 내용 작성 시작-->
<div id ="main">
    <form id="main2" method="post">
        <h1 id="review">REVIEW</h1>
        {% csrf_token %}<!--사용자의 의도와 관계 없이 행해지는 공격 방어-->
            <h3 id ="title">제목</h3>
            <p>{{form.title}}</P>
            {% for error in form.title.errors %}<!--에러감지-->
                <p>{{error}}</p>
            {% endfor %}
            <h3 id = "content">내용</h3>
            <p>{{form.content}}</P>
            {% for error in form.content.errors %}<!--에러감지-->
                <p>{{error}}</p>
            {% endfor %}
            <br>
            <button id = "but" type = 'submit'>작성 완료</button>
        </form>
</div>
{% endblock %}

{% block style %}<!--각 페이지별 스타일시트 적용 부분 시작-->
<style>
    /*리뷰*/
    #main{
        width:800px;
        height: 850px;
        margin: auto;
        margin-top:100px;
        margin-bottom: 100px;
        border: solid 2px rgba(255, 255, 255, 0.75) ;
        border-radius: 20px;
        padding : 50px;
    }
    #main2{
        width: 600px;
        margin: auto;
    }
    #review{
        font-size: 40px;
        font-weight: 300px;
        margin-top: 30px;
    }
    #title, #content{
        font-size: 17px;
        font-weight: 300px;
    }
    #id_content{
        resize: none;
    }
    /*버튼*/
    #but{
        border: none;
        width:600px;
        height: 50px;
        border-radius: 6px;
        color:#ffffff;
        background-color: #e44c65;
        font-size: 15px;
        font-weight: 500;
        cursor: pointer;
    }




</style>
{% endblock %}


effortlessfolder/review/templates/review/post_list.html
<!--
	review 템플릿의 post_list.html입니다.
	작성된 리뷰의 목록을 보여주고 리뷰작성페이지로 이동 가능한 버튼을 제공하는 페이지입니다.
-->

{% extends './base.html' %}<!--review템플릿의 base.html 템플릿 확장-->

{% block main1 %}<!--메인에 들어갈 내용 작성 시작-->
    <h1 id = "pageTitle">CONTENTS REVIEW</h1>
    <br>

    <div id="link"><!--리뷰작성을 위한 버튼-->
        <a href= {% url 'review:post-create' %}>
            <button type="submit">리뷰 작성하기</button>
        </a>
    </div>
<br>
    <table id = "create"><!--리뷰 목록-->
        <tr id="infor">
            <td>ID</td>
            <td class="title">제목</td>
            <td class = "date">작성일</td>
            <td class = "mod">수정일</td>
        </tr>
        {% for post in posts %}<!--for문을 이용해 저장된 모든 리뷰를 표시-->
        <tr id="list">
            <td>{{post.id}}</td>
            <td class = "title"><a href={% url 'review:post-detail' post.id %}>{{post.title}}</a></td> 
            <td class = "date">{{post.dt_created}}</td>
            <td class = "mod">{{post.dt_modified}}</td>
        </tr>
        {% endfor %}
     </table>
{% endblock %}

{% block style %}
<style>
    /*버튼*/
    #link{
        margin-bottom: 20px;
    }
    #link button{
        border: none;
        float: right;
        width:120px;
        height: 35px;
        border-radius: 6px;
        color:#ffffff;
        background-color: #e44c65;
        font-weight: 500;
        cursor: pointer;
    }
    /*리뷰목록테이블*/
    .title{
        width: 500px;
    }
    .date{
        width:250px;
    }
    .mod{
        width:250px;
    }
    #create{
        width : 1000px;
        margin : auto;
        margin-top : 10px;
        margin-bottom: 100px;
    }
    #infor,#list{
        text-align: center;
    }
    #list{
        background-color: #1c1d26;
    }
    /*기타*/
    h1, table, form, #search, #link{
        width:1000px;
        margin:auto;
    }
    #pageTitle{
        text-align: center;
        margin: auto;
        margin-top:120px;
        width : 300px;
        height: 70px;
        font-size : 30px;
        font-weight: 600;
        position: relative;
    }

</style>
{% endblock %}