effortlessfolder/effortless/urls.py
from django.contrib import admin
from django.urls import path, include

# 각 앱마다 url 연결
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('ott.urls')),
    path('', include('review.urls')),
]

effortlessfolder/ott/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# ott 관련 url
app_name = 'ott'
urlpatterns = [
    path('', views.main, name ='main'),
    path('amazon/', views.amazon, name='amazon'),
    path('hulu/', views.hulu, name='hulu'),
    path('disney/', views.disney, name='disney'),
    path('netflix/', views.netflix, name='netflix'),
    
    

    


]

effortlessfolder/review/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# 리뷰 관련 url 
app_name = 'review'
urlpatterns = [
    
    path('posts/', views.post_list, name='post-list'),
    path('posts/new', views.post_create, name='post-create'),
    path('posts/<int:post_id>/', views.post_detail, name='post-detail'),
    path('posts/<int:post_id>/edit', views.post_update, name='post-update'),
    path('posts/<int:post_id>/delete', views.post_delete, name='post-delete'),
    # path('posts/search', views.search, name='search'),

    
    

    


]

effortlessfolder/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

#user에 관련된 url 설정
app_name = 'user'
urlpatterns = [
    
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    

    


]

effortlessfolder/ott/models.py
from django.db import models

# Create your models here.
# 넷플릭스 데이블
class Netflix(models.Model):
    type = models.CharField(max_length=200)
    title = models.CharField(max_length=50, unique =True)
    director =  models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    release_year = models.IntegerField()
    rating = models.CharField(max_length=200)
    duration = models.CharField(max_length=200)
    listed_in = models.CharField(max_length=200)
    description= models.TextField(null=True)

    def __str__(self):
        return self.title
# 훌루 테이블
class Hulu(models.Model):
    type = models.CharField(max_length=200)
    title = models.CharField(max_length=50, unique =True)
    release_year = models.IntegerField()
    rating = models.CharField(max_length=200)
    duration = models.CharField(max_length=200)
    listed_in = models.CharField(max_length=200)
    description= models.TextField(null=True)

    def __str__(self):
        return self.title
    
# 아마존 테이블
class Amazon(models.Model):
    type = models.CharField(max_length=200)
    title = models.CharField(max_length=50, unique =True)
    director =  models.CharField(max_length=200)
    release_year = models.IntegerField()
    rating = models.CharField(max_length=200)
    duration = models.CharField(max_length=200)
    listed_in = models.CharField(max_length=200)
    description= models.TextField(null=True)

    def __str__(self):
        return self.title
# 디즈니 테이블
class Disney(models.Model):
    type = models.CharField(max_length=200)
    title = models.CharField(max_length=50, unique =True)
    director =  models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    release_year = models.IntegerField()
    rating = models.CharField(max_length=200)
    duration = models.CharField(max_length=200)
    listed_in = models.CharField(max_length=200)
    description= models.TextField(null=True)

    def __str__(self):
        return self.title
    

effortlessfolder/ott/views.py
from django.shortcuts import render

from datetime import datetime
from .models import Amazon, Disney, Hulu, Netflix
from django.db.models import Q
from django.contrib import messages
from django.core.paginator import Paginator


# Create your views here.


   

# 메인 페이지 데이터베이스 ott_netflix 테이블에서 데이터 가져오기
def main(request):
    today = datetime.today().date()
    movies = Netflix.objects.all()
    
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    
    
    # 조회
    movies = Netflix.objects.order_by('id')
    kw = request.GET.get('kw','')
    

    # 페이징처리
    paginator = Paginator(movies, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    
    
    
    

    
    if 'kw': # 만약 검색어가 존재하면
        movies = movies.filter(title__icontains= kw) # 해당 검색어를 포함한 queryset 가져오기
        paginator = Paginator(movies, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        
        


    context = {'date': today, 'movies': page_obj , 'page': page ,'kw':kw }

    return render(request, 'ott/main.html', context)
#데이터베이스 ott_amazon 테이블에서 데이터 가져오기
def amazon(request):
    today = datetime.today().date()
    movies = Amazon.objects.all()
    
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    
    
    # 조회
    movies = Amazon.objects.order_by('id')
    kw = request.GET.get('kw','')
    

    # 페이징처리
    paginator = Paginator(movies, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    
    
    
    

    
    if 'kw': # 만약 검색어가 존재하면
        movies = movies.filter(title__icontains= kw) # 해당 검색어를 포함한 queryset 가져오기
        paginator = Paginator(movies, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        
        


    context = {'date': today, 'movies': page_obj , 'page': page ,'kw':kw }

    return render(request, 'ott/amazon.html', context)
    
#데이터베이스 ott_hulu 테이블에서 데이터 가져오기

def hulu(request):
    today = datetime.today().date()
    movies = Hulu.objects.all()
    
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    
    
    # 조회
    movies = Hulu.objects.order_by('id')
    kw = request.GET.get('kw','')
    

    # 페이징처리
    paginator = Paginator(movies, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    
    
    
    

    
    if 'kw': # 만약 검색어가 존재하면
        movies = movies.filter(title__icontains= kw) # 해당 검색어를 포함한 queryset 가져오기
        paginator = Paginator(movies, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        
        


    context = {'date': today, 'movies': page_obj , 'page': page ,'kw':kw }

    return render(request, 'ott/hulu.html', context)
#데이터베이스 ott_disney 테이블에서 데이터 가져오기
def disney(request):
    today = datetime.today().date()
    movies = Disney.objects.all()
    
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    
    
    # 조회
    movies = Disney.objects.order_by('id')
    kw = request.GET.get('kw','')
    

    # 페이징처리
    paginator = Paginator(movies, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    
    
    
    

    
    if 'kw': # 만약 검색어가 존재하면
        movies = movies.filter(title__icontains= kw) # 해당 검색어를 포함한 queryset 가져오기
        paginator = Paginator(movies, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        
        


    context = {'date': today, 'movies': page_obj , 'page': page ,'kw':kw }

    return render(request, 'ott/disney.html', context)
    


def netflix(request):
    today = datetime.today().date()
    movies = Netflix.objects.all()
    context = {'date':today,'movies' :movies}
    
    return render(request, 'ott/netflix.html', context=context)

effortlessfolder/ott/templates/ott/amazon.html
<!--
	ott 템플릿의 amazon.html입니다.
	아마존 프라임의 컨텐츠 목록을 표시하고 다른 배급사의 페이지로 이동 가능한 메뉴바를 제공하며
  컨텐츠 제목 검색을 통해 아마존 프라임이 제공하는 컨텐츠들을 검색할 수 있습니다. 
-->


{% extends './base.html' %} <!--ott템플릿의 base.html 템플릿 확장-->
{% load static %}  
{% block main1 %}<!--메인에 들어갈 내용 작성 시작-->

<!--메인부분 상단 배급사 이미지(아마존 프라임)-->
<h2 style=" font-size:50px;" align = 'center'><img style = "vertical-align : middle"; src="{% static 'ott/prime.png' %}" height ="110" width="220" /></h2>

<!--다른 배급사(넷플릭스, 디즈니플러스, 훌루) 페이지로 이동 가능한 메뉴바-->
<ul id="menu" align = "center">
  <li><a href= {% url 'ott:main' %}><img style = "vertical-align : middle"; src="{% static 'ott/netflix.png' %}" height ="40" width="80" /></a></li>
  <li><a href= {% url 'ott:amazon' %}><img style = "vertical-align : middle"; src="{% static 'ott/prime.png' %}" height ="40" width="80" /></a></li>
  <li><a href= {% url 'ott:hulu' %}><img style = "vertical-align : middle"; src="{% static 'ott/hulu.png' %}" height ="40" width="80" /></a></li>
  <li><a href= {% url 'ott:disney' %}><img style = "vertical-align : middle"; src="{% static 'ott/disney.png' %}" height ="40" width="80" /></a></li>
</ul>
<br>
<!--아마존 제공 컨텐츠 한정 검색 기능-->
<form action ="{% url 'ott:amazon' %}" method="GET">
  <div style = "width : 800px; height : 50px; margin:auto;">
    <button style = "width : 100px; margin-bottom : 20px; margin : 0px; float : right;font-size: 15px; "> 검색 </button>
    <input style = "margin-bottom : 20px; width : 650px"; type="text" placeholder="contents name" name="kw" value= {{kw}}>
  </div>
</form>
<!--현재 날짜의 ott서비스임을 표시-->
<div id="ott">
  <h1 style=" font-size:15px;">{{ date }}의 OTT 서비스</h1>
</div>
<br>
<!--아마존 프라임의 데이터베이스 스키마 메인화면에 제공-->
<table class="table">
  <thead>
    <tr>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">#</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Type</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Title</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Director</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Release Year</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Rating</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Duration</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">listed_in</td>
    </tr>
  </thead>
<!--아마존 프라임의 데이터베이스 저장 데이터 메인화면에 제공-->
 {% for movie in movies %}<!--for문을 사용해 저장된 모든 컨텐츠 표시-->
  <tbody>
    <tr>
      <td id="td1" style = " font-size : 20px;" scope="row">{{movie.id}}</td>
      <td style = " font-size : 15px;">{{movie.type}}</td>
      <td style = " font-size : 15px;">{{movie.title}}</td>
      <td style = " font-size : 15px;">{{movie.director}}</td>
      <td style = " font-size : 15px;">{{movie.release_year}}</td>
      <td style = " font-size : 15px;">{{movie.rating}}</td>
      <td style = " font-size : 15px;">{{movie.duration}}</td>
      <td id="td2" style = " font-size : 15px;">{{movie.listed_in}}</td>
    </tr>
    <td id="d" style = " font-size : 13px;" colspan="9">{{movie.description}}</td>
  </tbody>
 {% endfor %}
</table>
<!--페이징 구현부-->
<div id="paging">
  <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center">
      <!-- 이전페이지 -->
      {% if movies.has_previous %}
      <li class="page-item">
          <a class="page-link" href="?page={{ movies.previous_page_number }}">이전</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
      </li>
      {% endif %}
      <!-- 페이지리스트 -->
      {% for page_number in movies.paginator.page_range %}
      {% if page_number >= movies.number|add:-5 and page_number <= movies.number|add:5 %}
          {% if page_number == movies.number %}
          <li class="page-item active" aria-current="page">
              <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
          {% else %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
          {% endif %}
      {% endif %}
      {% endfor %}
      <!-- 다음페이지 -->
      {% if movies.has_next %}
      <li class="page-item">
          <a class="page-link" href="?page={{ movies.next_page_number }}">다음</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
      </li>
      {% endif %}
  </ul>
  <!-- 페이징처리 끝 -->
</div>

{% endblock %}

{% block style %} <!--각 페이지별 스타일시트 적용 부분 시작-->

<style>
  /*폰트*/
@font-face {
	font-family: 'Chosunilbo_myungjo';
	src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/Chosunilbo_myungjo.woff') format('woff');
	font-weight: normal;
	font-style: normal;
}
@font-face {
    font-family: 'Cafe24Ssurround';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2105_2@1.0/Cafe24Ssurround.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
/*검색*/
input{
  float:left;
  }
button{
  border: 1px solid #E44C65;
  border-radius: 10px;
  background-color:#E44C65;
  color:white;
  width:200px;
  height:50px;
  display: inline-block;
  vertical-align: top;
  font-size: 13px;
  cursor: pointer;
  margin-top: 20px;
}
/*페이징*/
#paging ul{
  text-align: center;
}
#paging li{
  display: inline-block;
  width: 50px;
  height: 15px;
}
/*메뉴바*/
#menu{
  list-style:none;
  width:1000px;
  height:60px;
  padding-left: 200px;
  padding-right: 200px;
  margin:auto;
  background-color: rgba(255, 255, 255, 0.075);
  align-items: center;
}
#menu li{
  float:left;
  width:150px;
  position:relative;
  height: 60px;
  margin:0;
  padding:0;
  line-height: 60px;
  text-align: center;
  color: white;
}
/*테이블*/
table{
  font-family: 'Chosunilbo_myungjo';
}
.table {
  width:1000px;
  margin:auto;
  background-color: #1C1D26;
  border-collapse: collapse;
  text-align: left;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}
td {
  text-align: center;
  width : 1000px;
}
#d{
  background-color:rgba(255, 255, 255, 0.075);
  border-bottom:solid 15px #1C1D26;
}
/*기타*/
#ott{
  padding-top: 20px;
  padding-left:20px;
}
#ott h1{
  color:rgba(255, 255, 255, 0.712);
  text-align: center;
  font-family: 'Cafe24Ssurround';
}
h2{
  margin: auto;
  padding-top: 80px;
  padding-bottom: 30px;
}
a{
  border-bottom: none;
}
</style>

{% endblock %}

effortlessfolder/ott/templates/ott/base.html
<!--
	ott 템플릿의 base.html입니다.
	모든 페이지에 동일하게 적용되는 속성들을 base.html에 작성하여 템플릿 확장에 사용합니다.
	ott 템플릿에서는 ott서비스의 검색 기능, 컨텐츠 표시 구현을 중점으로 페이지를 제작합니다.
-->

{% load static %} <!--static 폴더(css,img파일)를 로드-->
<!DOCTYPE HTML>

<!--
	Landed by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

<html>
	<head>
		<title>effortless</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href= '../../static/ott/main.css' />
		<noscript><link rel="stylesheet" href= '../../static/ott/noscript.css'/></noscript>
	</head>

	<body class="is-preload">
		<div id="page-wrapper">
			<!-- Header -->
				<header id="header"> <!--상단의 네비게이션바-->
					<h1 id="logo"><a href="{% url 'ott:main' %}">Effortless</a></h1> <!--네비게이션 바 좌측의 Effortless 클릭 시 메인페이지로 이동-->
					<nav id="nav">
						<ul>
                                {% if user.is_authenticated %} <!--사용자가 로그인 상태인 경우의 상단 네비게이션 바 상태 정의-->
								<li style=" font-size:15px;" >{{user.username}}님 환영합니다.</li>
								<li><a style=" font-size:15px;" href="{% url 'user:logout' %}">Logout</a></li>
                                {% else %} <!--사용자가 로그인하지 않은 상태인 경우의 상단 네비게이션 바 상태 정의-->
								<li><a style=" font-size:15px;" href="{% url 'user:login' %}">LogIn</a></li>
								<li><a style=" font-size:15px;" href="{% url 'user:signup' %}">Signup</a></li>
                                {% endif %}
								<li> <!--로그인 여부와 관계 없이 리뷰 페이지로 이동하는 링크-->
									<a style=" font-size:15px;" href="{% url 'review:post-list' %}">Review</a>
								</li>

						</ul>
					</nav>
						{% block header %} <!--템플릿 확장 시 header block 내용 추가를 위한 블럭-->

						{% endblock %}
				</header>

			<!-- Main -->

				{% block main1 %} <!--템플릿 확장 시 main1 block 내용 추가를 위한 블럭-->

				{% endblock main1 %}


			<!-- Footer -->
				<footer id="footer"> <!--모든 페이지의 하단에 위치할 footer 작성-->
					<ul class="copyright">
						<li>최대효율의 법칙. All rights reserved.</li>
					</ul>
				</footer>
		</div>
		{% block style %} <!--각 페이지의 stylesheet 내용 추가를 위한 블럭-->
		{% endblock %}
	</body>
</html>

effortlessfolder/ott/templates/ott/disney.html
<!--
	ott 템플릿의 disney.html입니다.
	디즈니 플러스의 컨텐츠 목록을 표시하고 다른 배급사의 페이지로 이동 가능한 메뉴바를 제공하며
  컨텐츠 제목 검색을 통해 디즈니 플러스가 제공하는 컨텐츠들을 검색할 수 있습니다. 
-->

{% extends './base.html' %}<!--ott템플릿의 base.html 템플릿 확장-->
{% load static %}  
{% block main1 %}<!--메인에 들어갈 내용 작성 시작-->

<!--메인부분 상단 배급사 이미지(디즈니 플러스)-->
<h2 style=" font-size:50px;" align = 'center'><img style = "vertical-align : middle"; src="{% static 'ott/disney.png' %}" height ="110" width="210" /></h2>

<!--다른 배급사(넷플릭스, 아마존 프라임, 훌루) 페이지로 이동 가능한 메뉴바-->
<ul id="menu" align = "center">
  <li><a href= {% url 'ott:main' %}><img style = "vertical-align : middle"; src="{% static 'ott/netflix.png' %}" height ="40" width="80" /></a></li>
  <li><a href= {% url 'ott:amazon' %}><img style = "vertical-align : middle"; src="{% static 'ott/prime.png' %}" height ="40" width="80" /></a></li>
  <li><a href= {% url 'ott:hulu' %}><img style = "vertical-align : middle"; src="{% static 'ott/hulu.png' %}" height ="40" width="80" /></a></li>
  <li><a href= {% url 'ott:disney' %}><img style = "vertical-align : middle"; src="{% static 'ott/disney.png' %}" height ="40" width="80" /></a></li>
</ul>
<br>
<!--디즈니 플러스 제공 컨텐츠 한정 검색 기능-->
<form action ="{% url 'ott:disney' %}" method="GET">
  <div style = "width : 800px; height : 50px; margin:auto;">
    <button style = "width : 100px; margin-bottom : 20px; margin : 0px; float : right;font-size: 15px;"> 검색 </button>
    <input style = "margin-bottom : 20px; width : 650px"; type="text" placeholder="contents name" name="kw" value= {{kw}}>
  </div>
</form>
<!--현재 날짜의 ott서비스임을 표시-->
<div id="ott">
  <h1 style=" font-size:15px;">{{ date }}의 OTT 서비스</h1>
</div>
<br>
<!--디즈니 플러스의 데이터베이스 스키마 메인화면에 제공-->
<table class="table">
  <thead>
    <tr>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">#</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Type</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Title</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Tirector</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Country</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Release Year</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Rating</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Duration</td>
      <td style = " font-size : 20px; font-weight: 400;" scope="col">Listed In</td>
    </tr>
  </thead>
<!--디즈니 플러스의 데이터베이스 저장 데이터 메인화면에 제공-->
 {% for movie in movies %}<!--for문을 사용해 저장된 모든 컨텐츠 표시-->
  <tbody>
    <tr>
      <td id="td1" style = " font-size : 20px;" scope="row">{{movie.id}}</td>
      <td style = " font-size : 15px;">{{movie.type}}</td>
      <td style = " font-size : 15px;">{{movie.title}}</td>
      <td style = " font-size : 15px;">{{movie.director}}</td>
      <td style = " font-size : 15px;">{{movie.country}}</td>
      <td style = " font-size : 15px;">{{movie.release_year}}</td>
      <td style = " font-size : 15px;">{{movie.rating}}</td>
      <td style = " font-size : 15px;">{{movie.duration}}</td>
      <td id="td2" style = " font-size : 15px;">{{movie.listed_in}}</td>
    </tr>
    <td id="d" style = " font-size : 13px;" colspan="9">{{movie.description}}</td>
  </tbody>
 {% endfor %}
</table>
<!--페이징 구현부-->
<div id="paging">
  <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center">
      <!-- 이전페이지 -->
      {% if movies.has_previous %}
      <li class="page-item">
          <a class="page-link" href="?page={{ movies.previous_page_number }}">이전</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
      </li>
      {% endif %}
      <!-- 페이지리스트 -->
      {% for page_number in movies.paginator.page_range %}
      {% if page_number >= movies.number|add:-5 and page_number <= movies.number|add:5 %}
          {% if page_number == movies.number %}
          <li class="page-item active" aria-current="page">
              <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
          {% else %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
          {% endif %}
      {% endif %}
      {% endfor %}
      <!-- 다음페이지 -->
      {% if movies.has_next %}
      <li class="page-item">
          <a class="page-link" href="?page={{ movies.next_page_number }}">다음</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
      </li>
      {% endif %}
  </ul>
  <!-- 페이징처리 끝 -->
</div>


{% endblock %}

{% block style %} <!--각 페이지별 스타일시트 적용 부분 시작-->

<style>
  /*폰트*/
  @font-face {
	font-family: 'Chosunilbo_myungjo';
	src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/Chosunilbo_myungjo.woff') format('woff');
	font-weight: normal;
	font-style: normal;
}
@font-face {
    font-family: 'Cafe24Ssurround';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2105_2@1.0/Cafe24Ssurround.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
/*검색*/
input{
  float:left;
  }
button{
  border: 1px solid #E44C65;
  border-radius: 10px;
  background-color:#E44C65;
  color:white;
  width:200px;
  height:50px;
  display: inline-block;
  vertical-align: top;
  font-size: 13px;
  cursor: pointer;
  margin-top: 20px;
}
/*페이징*/
#paging ul{
  text-align: center;
}
#paging li{
  display: inline-block;
  width: 50px;
  height: 15px;
}
/*메뉴바*/
#menu{
  list-style:none;
  width:1000px;
  height:60px;
  padding-left: 200px;
  padding-right: 200px;
  margin:auto;
  background-color: rgba(255, 255, 255, 0.075);
  align-items: center;
}
#menu li{
  float:left;
  width:150px;
  position:relative;
  height: 60px;
  margin:0;
  padding:0;
  line-height: 60px;
  text-align: center;
  color: white;
}
/*테이블*/
table{
  font-family: 'Chosunilbo_myungjo';
}
.table {
  width:1000px;
  margin:auto;
  background-color: #1C1D26;
  border-collapse: collapse;
  text-align: left;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}
td {
  text-align: center;
  width : 1000px;
}
#d{
  background-color:rgba(255, 255, 255, 0.075);
  border-bottom:solid 15px #1C1D26;
}
/*기타*/
#ott{
  padding-top: 20px;
  padding-left:20px;
}
#ott h1{
  color:rgba(255, 255, 255, 0.712);
  text-align: center;
  font-family: 'Cafe24Ssurround';
}
h2{
  margin: auto;
  padding-top: 80px;
  padding-bottom: 30px;
}
a{
  border-bottom: none;
}
</style>

{% endblock %}